In [19]:
# Label Encoding

In [20]:
import pandas as pd
import numpy as np

In [21]:
df=pd.DataFrame({
    'color':['red','blue','red','red','green','blue','green']
})

In [22]:
df

color
0    red
1   blue
2    red
3    red
4  green
5   blue
6  green

In [23]:
from sklearn.preprocessing import LabelEncoder

In [24]:
encoder=LabelEncoder()

In [25]:
encoder.fit_transform(df[['color']])

C:\Users\dodda\AppData\Roaming\Python\Python310\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 0, 2, 2, 1, 0, 1])

In [33]:
# Ordinal Encoding

In [27]:
from sklearn.preprocessing import OrdinalEncoder

In [28]:
df=pd.DataFrame({
    'size':['s','m','l','s','s','l','s','m']
})

In [29]:
df

size
0    s
1    m
2    l
3    s
4    s
5    l
6    s
7    m

In [30]:
encoder=OrdinalEncoder(categories=[['s','m','l']])

In [31]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [0.],
       [0.],
       [2.],
       [0.],
       [1.]])

In [32]:
encoder.transform([['s']])

C:\Users\dodda\AppData\Roaming\Python\Python310\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[0.]])